### ISSUE TITLE
npm package broken

### ISSUE THREAD

**Issue by leider** [jpmonette/feed#77]
**Describe the bug**
The current npm release exposes a typescript class not a javascript class

**To Reproduce**
1. Create a pure javascript nodejs file
2. require feed
3. try to instantiate the Feed class

**Expected behavior**
Works as before

**Actual behavior**
Kills server

**Screenshots**

**Versions (please complete the following information):**
 - NodeJS: 10 
 - TypeScript: none
 - npm/yarn: 5.6.0 (npm)
 - feed: latest

**Additional context**
None

**Comment by jpmonette** [comment]
@leider Can you provide code sample please?

**Comment by leider** [comment]
What exactly is not clear in the bug description?

**Comment by jpmonette** [comment]
@leider There's no such thing as a TypeScript class - the code is compiled to JavaScript in the `lib/` directory by `tsc`.

My assumption here (without the code sample you are trying to run) is that you are trying to import the  module using a `require()` instead of an `import`. Considering the latest version is now using named imports, in ES6, you import it as described in the README:

```ts
import { Feed } from 'feed';
```

If you want to stick with the old way of importing modules, you should be able to do the following:

```js
const Feed = require('feed').Feed;
```

As I'm not sure if this was the situation you were facing, please confirm if this solves your issue.

**Comment by leider** [comment]
Thanks. This is the situation. I will try as soon as I can and give feedback.

**Comment by leider** [comment]
Checked it. Thanks for the clarification. Problem was me not understanding excatly what was the problem. Documentation fix is appreciated!

**Comment by danger89** [comment]
`const Feed = require('feed').Feed;` line saved me 2 hours of my day. Please document this !
